name: Semantic Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv sync --extra dev
    
    - name: Run tests
      run: |
        uv run pytest --cov=mcp_devbench --cov-report=term-missing
    
    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@v9.14
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish package to PyPI
      if: steps.release.outputs.released == 'true'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
    
    - name: Publish package to GitHub Release
      if: steps.release.outputs.released == 'true'
      uses: python-semantic-release/upload-to-gh-release@v9.14.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.release.outputs.tag }}
